#Curso: Pós graduação em Ciência de dados e Big Data - 2021
#Matéria: Machine Learning
#Aluno: Pedro Martins

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
download_url = 'https://drive.google.com/uc?export=download&id='
url_drive_file = 'https://docs.google.com/spreadsheets/d/1V02vVWFAmxMAA7Wq_ghVLc7Qix1SC9i6/edit#gid=1729128232'

download_path = download_url + url_drive_file.split('/')[-2]

automoveis = pd.read_excel(download_path, 
                           
                sheet_name = 'Plan1',
                 header=0)

automoveis.head()

Fabricante Combustível  Portas  ... Potência (HP) Pico RPM     Preço
0  alfa-romeo         gas     2.0  ...        111,00  5000,00  13495,00
1  alfa-romeo         gas     2.0  ...        111,00  5000,00  16500,00
2  alfa-romeo         gas     2.0  ...        154,00  5000,00  16500,00
3        audi         gas     4.0  ...        102,00  5500,00  13950,00
4        audi         gas     4.0  ...        115,00  5500,00  17450,00

[5 rows x 15 columns]

In [ ]:
automoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Fabricante           203 non-null    object 
 1   Combustível          200 non-null    object 
 2   Portas               203 non-null    float64
 3   Estilo Chassis       205 non-null    object 
 4   Tração               205 non-null    object 
 5   Comprimento          205 non-null    object 
 6   Largura              205 non-null    object 
 7   Altura               205 non-null    object 
 8   Tipo de motor        205 non-null    object 
 9   Número de cilindros  205 non-null    object 
 10  Tamanho do motor     205 non-null    object 
 11  Tipo de injeção      205 non-null    object 
 12  Potência (HP)        205 non-null    object 
 13  Pico RPM             205 non-null    object 
 14  Preço                205 non-null    object 
dtypes: float64(1), object(14)
memory usage: 

In [ ]:
automoveis.shape

(205, 15)

In [ ]:
automoveis.columns

Index(['Fabricante', 'Combustível', 'Portas', 'Estilo Chassis', 'Tração',
       'Comprimento', 'Largura', 'Altura', 'Tipo de motor',
       'Número de cilindros', 'Tamanho do motor', 'Tipo de injeção',
       'Potência (HP)', 'Pico RPM', 'Preço'],
      dtype='object')

In [ ]:
automoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Fabricante           203 non-null    object 
 1   Combustível          200 non-null    object 
 2   Portas               203 non-null    float64
 3   Estilo Chassis       205 non-null    object 
 4   Tração               205 non-null    object 
 5   Comprimento          205 non-null    object 
 6   Largura              205 non-null    object 
 7   Altura               205 non-null    object 
 8   Tipo de motor        205 non-null    object 
 9   Número de cilindros  205 non-null    object 
 10  Tamanho do motor     205 non-null    object 
 11  Tipo de injeção      205 non-null    object 
 12  Potência (HP)        205 non-null    object 
 13  Pico RPM             205 non-null    object 
 14  Preço                205 non-null    object 
dtypes: float64(1), object(14)
memory usage: 

In [ ]:
#dados numericos
automoveis.describe()

Portas
count  203.000000
mean     3.123153
std      0.994841
min      2.000000
25%      2.000000
50%      4.000000
75%      4.000000
max      4.000000

In [ ]:
#dados categoricos
automoveis.select_dtypes(include='object').describe()

Fabricante Combustível Estilo Chassis  ... Potência (HP) Pico RPM     Preço
count         203         200            205  ...           205      205       205
unique         22           2              5  ...            60       25       187
top        toyota         gas          sedan  ...         68,00  5500,00  13207,13
freq           32         180             96  ...            19       37         4

[4 rows x 14 columns]

#Remoção de linhas

###Remoção de linhas onde portas é nulo
Nesse passo removi duas linhas que tinham valor de porta nulo. Decidi fazer isso pois não consegui pensar em um valor para preencher o campo e porque são apenas duas linhas.


In [ ]:
automoveis[automoveis['Portas'].isnull()]

Fabricante Combustível  Portas  ... Potência (HP) Pico RPM     Preço
26      dodge         gas     NaN  ...        102,00  5500,00   8558,00
61      mazda      diesel     NaN  ...         64,00  4650,00  10795,00

[2 rows x 15 columns]

In [ ]:
automoveis['Portas'].unique()

array([ 2.,  4., nan])

In [ ]:
automoveis = automoveis[automoveis['Portas'].notna()] 

###Remoção de linhas onde combustível é nulo
Nesse passo removi duas linhas que tinham valor de porta nulo. Decidi fazer isso pois não consegui pensar em um valor para preencher o campo e porque são apenas 5 linhas.


In [ ]:
automoveis[automoveis['Combustível'].isnull()]

Fabricante Combustível  Portas  ... Potência (HP) Pico RPM     Preço
117   plymouth         NaN     2.0  ...        102,00  5500,00   7957,00
118   plymouth         NaN     4.0  ...         68,00  5500,00   6229,00
119   plymouth         NaN     4.0  ...         68,00  5500,00   6692,00
125    porsche         NaN     2.0  ...        207,00  5900,00  34028,00
139     subaru         NaN     4.0  ...         82,00  4800,00   7126,00

[5 rows x 15 columns]

In [ ]:
automoveis['Combustível'].unique()

array(['gas', 'diesel', nan], dtype=object)

In [ ]:
automoveis = automoveis[automoveis['Combustível'].notna()] 

###Remoção de linhas onde Fabricante é nulo
Nesse passo removi duas linhas que tinham valor de porta nulo. Decidi fazer isso pois não consegui pensar em um valor para preencher o campo e porque são apenas duas linhas.


In [ ]:
automoveis[automoveis['Fabricante'].isnull()]

Fabricante Combustível  Portas  ... Potência (HP) Pico RPM     Preço
203        NaN         gas     4.0  ...        121,00  4250,00  21105,00
204        NaN         gas     2.0  ...        101,00  6000,00  10945,00

[2 rows x 15 columns]

In [ ]:
automoveis['Fabricante'].unique()

array(['alfa-romeo', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo', nan],
      dtype=object)

In [ ]:
automoveis = automoveis[automoveis['Fabricante'].notna()] 

In [ ]:
automoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 196 entries, 0 to 202
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Fabricante           196 non-null    object 
 1   Combustível          196 non-null    object 
 2   Portas               196 non-null    float64
 3   Estilo Chassis       196 non-null    object 
 4   Tração               196 non-null    object 
 5   Comprimento          196 non-null    float64
 6   Largura              196 non-null    float64
 7   Altura               196 non-null    float64
 8   Tipo de motor        196 non-null    object 
 9   Número de cilindros  196 non-null    object 
 10  Tamanho do motor     196 non-null    object 
 11  Tipo de injeção      196 non-null    object 
 12  Potência (HP)        196 non-null    object 
 13  Pico RPM             196 non-null    object 
 14  Preço                196 non-null    object 
dtypes: float64(4), object(11)
memory usage: 

###Importante!
Professor, não consegui pensar em nenhuma forma que fizesse sentido de preenchimento dos campos nulos. Portanto, removi todas as linhas com registros nulos rsrs.

#Alteração de tipos de campo

###Alteração da coluna Preço para float
Nesse passo foi necessário fazer a alteração do campo para float

In [ ]:
automoveis['Comprimento'] = automoveis['Comprimento'].str.replace(',', '.').astype(float)
automoveis['Largura'] = automoveis['Largura'].str.replace(',', '.').astype(float)
automoveis['Altura'] = automoveis['Altura'].str.replace(',', '.').astype(float)

###Alteração da coluna Número de cilindros para int

Nesse passo fiz a alteração do valor por extenso para número e alterei o tipo da coluna

In [ ]:
automoveis['Número de cilindros'].unique()

array([4, 6, 5, 3, 'doze', 2, 'oito'], dtype=object)

In [ ]:
automoveis.loc[automoveis['Número de cilindros'] == 'doze','Número de cilindros'] = 12
automoveis.loc[automoveis['Número de cilindros'] == 'oito','Número de cilindros'] = 8

In [ ]:
automoveis['Número de cilindros'].unique()

array([4, 6, 5, 3, 12, 2, 8], dtype=object)

In [ ]:
automoveis['Número de cilindros'] = automoveis['Número de cilindros'].astype(int)

###Alteração da coluna Tamanho do motor para int
Nesse passo foi necessário fazer a alteração do campo para float e depois int

In [ ]:
automoveis['Tamanho do motor'].unique()

array(['130,00', '152,00', '109,00', '136,00', '131,00', '108,00',
       '164,00', '209,00', '61,00', '90,00', '98,00', '122,00', '156,00',
       '92,00', '79,00', '110,00', '111,00', '119,00', '258,00', '326,00',
       '91,00', '70,00', '80,00', '140,00', '134,00', '183,00', '234,00',
       '308,00', '304,00', '97,00', '103,00', '120,00', '181,00',
       '151,00', '194,00', '203,00', '132,00', '121,00', '146,00',
       '171,00', '161,00', '141,00', '173,00', '145,00'], dtype=object)

In [ ]:
automoveis['Tamanho do motor'] = automoveis['Tamanho do motor'].str.replace(',', '.').astype(float).astype(int)

###Alteração da coluna Pico RPM para float
Nesse passo foi necessário fazer a alteração do campo para float

In [ ]:
automoveis['Pico RPM'].unique()

array(['5000,00', '5500,00', 580000, '4250,00', '5400,00', '5100,00',
       '4800,00', '6000,00', '5800,00', '4750,00', '4200,00', '4350,00',
       '4500,00', '5200,00', '4150,00', '5600,00', '5900,00', '5750,00',
       '5125,37', '5250,00', '4900,00', '4400,00', '6600,00', '5300,00'],
      dtype=object)

In [ ]:
automoveis['Pico RPM'] = automoveis['Pico RPM'].str.replace(',', '.').astype(float)

###Alteração da coluna Preço para float
Nesse passo foi necessário fazer a alteração do campo para float

In [ ]:
automoveis['Preço'] = automoveis['Preço'].str.replace(',', '.').astype(float)

###Alteração da coluna Portas para int
Nesse passo foi necessário fazer a alteração do campo para int

In [ ]:
automoveis['Portas'] = automoveis['Portas'].astype(int)

###Alteração da coluna Potência para float
Nesse passo foi necessário fazer a alteração do campo para int

In [ ]:
automoveis['Potência (HP)'].unique()

array(['111,00', '154,00', '102,00', '115,00', '110,00', '140,00',
       '160,00', '101,00', '121,00', '182,00', '48,00', '70,00', '68,00',
       '88,00', '145,00', '58,00', '76,00', '60,00', '86,00', '100,00',
       '78,00', '90,00', '176,00', '262,00', '135,00', '84,00', '120,00',
       '72,00', '123,00', '155,00', '184,00', '175,00', '116,00', '69,00',
       '55,00', '97,00', '152,00', '200,00', '95,00', '142,00', '143,00',
       '207,00', '288,00', '104,26', '73,00', '82,00', '94,00', '62,00',
       '56,00', '112,00', '92,00', '161,00', '156,00', '52,00', '85,00',
       '114,00', '162,00', '134,00', '106,00'], dtype=object)

In [ ]:
automoveis['Potência (HP)'] = automoveis['Potência (HP)'].str.replace(',', '.').astype(float).astype(int)

#Preparação de dados finalizada

In [ ]:
automoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 196 entries, 0 to 202
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Fabricante           196 non-null    object 
 1   Combustível          196 non-null    object 
 2   Portas               196 non-null    int64  
 3   Estilo Chassis       196 non-null    object 
 4   Tração               196 non-null    object 
 5   Comprimento          196 non-null    float64
 6   Largura              196 non-null    float64
 7   Altura               196 non-null    float64
 8   Tipo de motor        196 non-null    object 
 9   Número de cilindros  196 non-null    int64  
 10  Tamanho do motor     196 non-null    int64  
 11  Tipo de injeção      196 non-null    object 
 12  Potência (HP)        196 non-null    int64  
 13  Pico RPM             194 non-null    float64
 14  Preço                196 non-null    float64
dtypes: float64(5), int64(4), object(6)
memor

In [ ]:
automoveis.head()

Fabricante Combustível  Portas  ... Potência (HP) Pico RPM    Preço
0  alfa-romeo         gas       2  ...           111   5000.0  13495.0
1  alfa-romeo         gas       2  ...           111   5000.0  16500.0
2  alfa-romeo         gas       2  ...           154   5000.0  16500.0
3        audi         gas       4  ...           102   5500.0  13950.0
4        audi         gas       4  ...           115   5500.0  17450.0

[5 rows x 15 columns]